name: navig_scroll
description: A Navigation & Scroll Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.1
  build_context: ^3.0.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true